joesdu/EasilyNET

Directory.Build.props
src/EasilyNET.IdentityServer.MongoStorage/EasilyNET.IdentityServer.MongoStorage.csproj
src/EasilyNET.Mongo.ConsoleDebug/EasilyNET.Mongo.ConsoleDebug.csproj
src/EasilyNET.Mongo.Extension/EasilyNET.Mongo.Extension.csproj
src/EasilyNET.Mongo.Extension/README.md
src/EasilyNET.Mongo.GridFS/EasilyNET.Mongo.GridFS.csproj
src/EasilyNET.Mongo/EasilyNET.Mongo.csproj

This is a patch release that addresses some issues reported since 2.19.0 was released.
An online version of these release notes is available [here](https://github.com/mongodb/mongo-csharp-driver/blob/master/Release%20Notes/Release%20Notes%20v2.19.1.md).
The list of JIRA tickets resolved in this release is available at [CSHARP JIRA project](https://jira.mongodb.org/issues/?jql=project%20%3D%20CSHARP%20AND%20fixVersion%20%3D%202.19.1%20ORDER%20BY%20key%20ASC).
Documentation on the .NET driver can be found [here](https://www.mongodb.com/docs/drivers/csharp/v2.19/).
There are no known backwards breaking changes in this release.

update mongodb.driver to 2.19.1

---

src/EasilyNET.Core/Enums/ENation.cs

修复基诺族描述特性值为空的情况。
根据第七次全国人口普查民族代码表新增 未定族称人口97。

fix-nationality

---

sample/WebApi.Test.Unit/WebApi.Test.Unit.csproj
src/Directory.Packages.props

在 `WebApi.Test.Unit.csproj` 文件中，将 `Serilog.Sinks.OpenTelemetry` 包的版本从 `4.1.0` 更新到了 `4.1.1-dev-00351`。 在 `Directory.Packages.props` 文件中，将 `MongoDB.Bson`、`MongoDB.Driver`、`MongoDB.Driver.Core` 和 `MongoDB.Driver.GridFS` 包的版本从 `2.28.0` 更新到了 `2.29.0`。

更新 Serilog 和 MongoDB 包版本

---

src/Directory.Packages.props

将 `Backport.System.Threading.Lock` 包的版本从 `3.1.1` 升级到 `3.1.4`。其他 XML 结构保持不变，进行了格式微调。

dump: 更新 Backport.System.Threading.Lock 包版本

---

.gitignore
EasilyNET.sln
docker-compose.basic.service.yml
docker-compose.mongo.rs.yml
otel-collector-config.yaml
sample/WebApi.Test.Unit/Program.cs
sample/WebApi.Test.Unit/ServiceModules/OpenTelemetryModule.cs
sample/WebApi.Test.Unit/appsettings.json

更新配置文件以支持 OpenTelemetry 和服务管理
- 更新 `.gitignore`，忽略 `MigrationBackup/` 目录。
- 添加 `otel-collector-config.yaml` 和 `openobserve` 服务配置。
- 在 `docker-compose.basic.service.yml` 中添加 `rabbit`、`aspire_dashboard` 和 `otel-collector` 服务。
- 在 `docker-compose.mongo.rs.yml` 中添加 MongoDB 服务配置。
- 在 `otel-collector-config.yaml` 中配置 OpenTelemetry 的接收器、处理器和导出器。
- 更新 `Program.cs` 中的 OpenTelemetry 配置。
- 在 `OpenTelemetryModule.cs` 中添加日志导出器配置。
- 移除 `appsettings.json` 中无效内容，保留 OpenTelemetry 端点配置。

feat: 添加OepnObserve和otel-conllector的使用案例.

---

src/EasilyNET.Mongo.ConsoleDebug/Subscribers/ActivityEventConsoleDebugSubscriber.cs

在 `ActivityEventConsoleDebugSubscriber.cs` 文件中，添加了对 `System.Net` 命名空间的引用。将 `endpoint` 变量类型更改为 `DnsEndPoint`，以更明确地处理网络端点。同时，调整了 JSON 字符串中的 "Port" 字段处理方式，直接使用 `endpoint?.Port`。

feat: 更新网络端点处理和JSON格式化

---

sample/WebApi.Test.Unit/Controllers/KeyedServiceTestController.cs

- 移除对 Microsoft.AspNetCore.Authorization 的引用，删除 [Authorize] 特性。
- 修改 KeyedServiceTestController 构造函数，使用 FromKeyedServices 注入 IKeyedServiceTest2。
- 更新 ShowHello2 方法实现，调用 kst2.ShowHello2()。
- 修改 KeyedServiceTest 类的 DependencyInjection 特性，新增 ShowHello2 方法实现。
- 新增 IKeyedServiceTest2 接口，定义 ShowHello2 方法，移除 ShowHello 的默认实现。

feat: 重构 KeyedServiceTestController 和相关类

---

sample/WebApi.Test.Unit/WebApi.Test.Unit.csproj
src/EasilyNET.AutoDependencyInjection/ServiceProviderExtension.cs
src/EasilyNET.Mongo.AspNetCore/TimeSeriesCollectionExtensions.cs

在 `WebApi.Test.Unit.csproj` 中，将 `OpenTelemetry.Exporter.OpenTelemetryProtocol` 和 `OpenTelemetry.Extensions.Hosting` 的版本从 `1.11.0-rc.1` 更新为 `1.11.0`。
在 `ServiceProviderExtension.cs` 中，简化了 `CreateInstance` 方法的构造函数获取逻辑，使用空合并运算符处理构造函数为 `null` 的情况，并抛出相应的异常信息。
在 `TimeSeriesCollectionExtensions.cs` 中，添加了 `#pragma warning disable IDE0130` 指令以禁用命名空间与文件夹结构不匹配的警告，并定义了命名空间 `Microsoft.Extensions.DependencyInjection`。

feat: 更新依赖项并简化构造函数逻辑

---

sample/WebApi.Test.Unit/WebApi.Test.Unit.csproj

更新了多个 OpenTelemetry 相关的包版本，从 1.10.x 升级到 1.11.x，同时移除了旧版本的包引用。

升级 OpenTelemetry 包版本至 1.11.x

---

src/Directory.Packages.props

将 `Spectre.Console.Json` 的版本从 `0.49.2-preview.0.72` 更新至 `0.49.2-preview.0.73`。

更新 Spectre.Console.Json 包版本

---

sample/WebApi.Test.Unit/WebApi.Test.Unit.csproj
src/Directory.Packages.props

更新了 `Microsoft.AspNetCore.Authentication.JwtBearer`、`Microsoft.AspNetCore.OpenApi`、`Microsoft.Extensions.Caching.StackExchangeRedis` 和 `Microsoft.Extensions.Http.Resilience` 的版本，从 9.0.1 和 9.1.0 更新到 9.0.2 和 9.2.0。 同时，`System.Management` 包版本从 9.0.1 更新到 9.0.2，`Spectre.Console.Json` 包版本从 0.49.2-preview.0.74 更新到 0.49.2-preview.0.75。 此外，多个 `Microsoft.Extensions` 相关的包版本也进行了更新，从 9.0.1 和 9.1.0 更新到 9.0.2 和 9.2.0。

更新多个 NuGet 包版本

---

test/EasilyNET.Test.Unit/EasilyNET.Test.Unit.csproj

将 `MSTest.TestAdapter` 和 `MSTest.TestFramework` 的版本从 `3.8.0` 升级到 `3.8.1`。

feat: 更新 MSTest 依赖项版本

---

sample/WebApi.Test.Unit/WebApi.Test.Unit.csproj
src/Directory.Packages.props

在 `WebApi.Test.Unit.csproj` 文件中，`Microsoft.VisualStudio.Azure.Containers.Tools.Targets` 的版本从 `1.21.1` 更新为 `1.21.2`。
在 `Directory.Packages.props` 文件中，`MongoDB.Driver` 的版本从 `3.2.0` 更新为 `3.2.1`。

feat: 更新依赖包版本

---

.github/ISSUE_TEMPLATE/bug.yml
.github/workflows/build_test.yml
.github/workflows/releaser.yml
sample/WebApi.Test.Unit/Dockerfile
sample/WebApi.Test.Unit/Program.cs
sample/WebApi.Test.Unit/WebApi.Test.Unit.csproj
src/Directory.Packages.props
src/EasilyNET.Mongo.ConsoleDebug/EasilyNET.Mongo.ConsoleDebug.csproj
test/EasilyNET.Core.Benchmark/EasilyNET.Core.Benchmark.csproj
test/EasilyNET.Test.Unit/EasilyNET.Test.Unit.csproj

- 在 `bug.yml` 中添加 .NET 10 作为默认选项。
- 修改 `build_test.yml` 和 `releaser.yml` 中的 `DOTNET_VERSION` 环境变量，支持多个 .NET 版本。
- 更新 `Dockerfile` 基础镜像为 .NET 10 预览版。
- 在 `Program.cs` 中禁用 XML 注释缺失警告。
- 将 `WebApi.Test.Unit.csproj`、`EasilyNET.Mongo.ConsoleDebug.csproj`、`EasilyNET.Core.Benchmark.csproj` 和 `EasilyNET.Test.Unit.csproj` 的目标框架更新为 .NET 10。
- 更新 `Directory.Packages.props` 中的 NuGet 包版本以兼容 .NET 10。

feat: 更新项目以支持 .NET 10 版本

---

sample/WebApi.Test.Unit/WebApi.Test.Unit.csproj
src/Directory.Packages.props

在 `WebApi.Test.Unit.csproj` 文件中，升级了 `Microsoft.AspNetCore.Authentication.JwtBearer` 和 `Microsoft.AspNetCore.OpenApi` 到版本 `9.0.3`，`Microsoft.Extensions.Http.Resilience` 到 `9.3.0`，以及 `Microsoft.VisualStudio.Azure.Containers.Tools.Targets` 到 `1.22.0`。同时，将 `Serilog.Sinks.File` 的版本更新至 `7.0.0-dev-02301`。
在 `Directory.Packages.props` 文件中，`Microsoft.Extensions.Resilience` 的版本也进行了相应的升级。

feat: 更新多个NuGet包版本

---

sample/WebApi.Test.Unit/Controllers/MongoTestController.cs
sample/WebApi.Test.Unit/WebApi.Test.Unit.csproj
src/EasilyNET.WebCore.Swagger/SwaggerGenOptionsExtensions.cs

在 `MongoTestController.cs` 中，`GetTest2` 方法的 `id` 参数添加了默认值 "1"。 在 `WebApi.Test.Unit.csproj` 中，更新 `Microsoft.VisualStudio.Azure.Containers.Tools.Targets` 的版本至 `1.22.1-Preview.1`。 在 `SwaggerGenOptionsExtensions.cs` 中，添加注释以禁用 ReSharper 对命名空间的检查。

feat: 调整依赖项版本

---

test/EasilyNET.Test.Unit/EasilyNET.Test.Unit.csproj

在 `EasilyNET.Test.Unit.csproj` 文件中，`MSTest.TestAdapter` 和 `MSTest.TestFramework` 的版本从 `3.8.2` 更新到了 `3.9.0-preview.25167.10`。这次更新引入了最新的功能和修复，提升了测试的稳定性和性能。

feat: 更新 MSTest 适配器和框架版本

---

src/EasilyNET.Core/ModuleInitializer.cs

微调计算欢迎消息前的空格数量的方式，提高代码可读性。注释掉不必要的输出语句，改为输出空行，确保在不同文本编码下的输出格式更加整洁一致。

feat: 优化欢迎消息输出格式

---

src/Directory.Packages.props

将 `Directory.Packages.props` 文件中的 `BouncyCastle.Cryptography` 包版本从 `2.6.0-beta.106` 更新为 `2.6.0-beta.114`。

feat: 更新 BouncyCastle.Cryptography 包版本

---

docker-compose.basic.service.yml
src/Directory.Packages.props

在 `docker-compose.basic.service.yml` 文件中，移除了环境变量 `DASHBOARD__TELEMETRYLIMITS__MAXMETRICSCOUNT=1000`，并更新了 `otel-collector` 的镜像地址。
在 `Directory.Packages.props` 文件中，更新了 `Spectre.Console.Json` 包的版本，从 `0.50.1-preview.0.2` 更改为 `0.50.1-preview.0.3`，同时移除了旧版本的声明。

更新 docker-compose 和包版本

---

sample/WebApi.Test.Unit/Program.cs
sample/WebApi.Test.Unit/WebApi.Test.Unit.csproj
src/EasilyNET.RabbitBus.AspNetCore/EventBus.cs
src/EasilyNET.RabbitBus.AspNetCore/Manager/PersistentConnection.cs

在 `Program.cs` 中添加了日志级别覆盖，以过滤特定日志信息。更新 `WebApi.Test.Unit.csproj` 中 `Serilog.Sinks.File` 的版本为稳定版 `7.0.0`。在 `EventBus.cs` 中优化了连接检查逻辑，确保在发布事件前检查连接状态并异步获取通道。最后，在 `PersistentConnection.cs` 中添加了连接状态检查和重连逻辑，改进了异常处理时的日志记录。

fix: 增强日志记录和连接管理功能

---

sample/WebApi.Test.Unit/WebApi.Test.Unit.csproj
src/Directory.Packages.props

更新了多个 NuGet 包的版本，包括 `Microsoft.AspNetCore.Authentication.JwtBearer`、`Microsoft.Extensions.Caching.StackExchangeRedis` 和 `System.Management`，将它们的版本从 `10.0.0-preview.3` 更新到 `10.0.0-preview.4`。
在 `Directory.Packages.props` 文件中，移除了旧版本的 `Microsoft.Extensions` 相关包，并添加了相应的新版本，确保所有相关依赖项都使用最新的预览版本 `10.0.0-preview.4`。

feat: 更新 NuGet 包版本至 .NET10-preview.4

---

sample/WebApi.Test.Unit/WebApi.Test.Unit.csproj
src/Directory.Packages.props

在 `WebApi.Test.Unit.csproj` 文件中，更新了以下 NuGet 包的版本：
- `Microsoft.AspNetCore.OpenApi` 从 `9.0.4` 更新到 `9.0.5`。
- `Microsoft.Extensions.Http.Resilience` 从 `9.4.0` 更新到 `9.5.0`。
在 `Directory.Packages.props` 文件中，`Microsoft.Extensions.Resilience` 的版本也从 `9.4.0` 更新到 `9.5.0`。

feat: 更新 NuGet 包版本

---

src/Directory.Packages.props

在 `Directory.Packages.props` 文件中，将 `BouncyCastle.Cryptography` 的版本号从 `2.6.0-beta.133` 更新为 `2.6.0`，以使用稳定版本的依赖项。

feat: 更新 BouncyCastle.Cryptography 版本为稳定版

---

test/EasilyNET.Test.Unit/EasilyNET.Test.Unit.csproj

将 `EasilyNET.Test.Unit.csproj` 文件中的测试相关包版本从预览版更新为正式版，包括 `Microsoft.NET.Test.Sdk`、`MSTest.TestAdapter` 和 `MSTest.TestFramework`。

feat: 更新测试包版本为正式版

---

sample/WebApi.Test.Unit/WebApi.Test.Unit.csproj

将 `Serilog.Sinks.OpenTelemetry` 的版本从 `4.2.0-dev-02302` 更新为 `4.2.0`，移除了开发版本，改为稳定版本。

feat: 更新 Serilog.Sinks.OpenTelemetry 版本

---

sample/WebApi.Test.Unit/WebApi.Test.Unit.csproj
src/Directory.Packages.props

更新了 `Microsoft.AspNetCore.Authentication.JwtBearer`、`Microsoft.Extensions.Caching.StackExchangeRedis`、`Serilog.Sinks.OpenTelemetry` 和 `System.Management` 的版本，从预览版 4 更新至预览版 5。 同时，将 `Spectre.Console.Json` 的版本从 `0.50.1-preview.0.10` 更新至 `0.50.1-preview.0.11`。 移除了旧版的 `Microsoft.Extensions` 相关包（版本 4），并添加了新版本（版本 5），以确保使用最新的功能和修复。

feat: 更新多个NuGet包至最新版, .NET 10-preview.5

---

src/EasilyNET.Core/Misc/AssemblyHelper.cs
src/EasilyNET.Mongo.AspNetCore/TimeSeriesCollectionExtensions.cs

在 AssemblyHelper 中，重载 FindTypesByAttribute 方法以支持 inherit 参数，默认值为 true，并更新相关 XML 注释。在 TimeSeriesCollectionExtensions 中，调用该方法时添加 inherit 参数并设置为 false，同时调整获取自定义属性的方式以处理多个属性。以处理时序集合对象被继承的情况下,创建时序集合及索引的时候产生异常.

chore: 更新 AssemblyHelper 和 TimeSeriesCollectionExtensions

---

sample/WebApi.Test.Unit/WebApi.Test.Unit.csproj
src/Directory.Packages.props

在 `WebApi.Test.Unit.csproj` 文件中，`Swashbuckle.AspNetCore` 的版本从 `8.1.4` 更新到 `9.0.1`，同时移除了 `System.Management` 的引用。
在 `Directory.Packages.props` 文件中，`Swashbuckle.AspNetCore.SwaggerGen` 和 `Swashbuckle.AspNetCore.SwaggerUI` 的版本也从 `8.1.4` 更新到 `9.0.1`。

feat: 更新 Swashbuckle.AspNetCore 版本至 9.0.1

---

src/EasilyNET.Mongo.AspNetCore/TimeSeriesCollectionExtensions.cs
src/EasilyNET.Mongo.Core/Attributes/TimeSeriesCollectionAttribute.cs

在 `TimeSeriesCollectionExtensions.cs` 中，更新了 `ExpireAfter` 的赋值逻辑，增加了条件判断以处理负值情况。 在 `TimeSeriesCollectionAttribute.cs` 中，移除了构造函数的 `ttl` 参数，删除了相关文档注释，并将 `ExpireAfter` 的类型从 `TimeSpan?` 改为 `double`，默认值设为 -1，以简化过期时间的处理。

fix: 修改过期时间处理逻辑和属性类型

---

src/EasilyNET.AutoDependencyInjection/Modules/ModuleApplicationBase.cs

将模块启用状态的检查逻辑合并到返回语句中，直接依赖于 `module.GetEnable(new(Services, ServiceProvider))` 的结果。这样做减少了代码复杂性，提高了可读性。

feat: 简化模块启用状态检查逻辑

---

sample/WebApi.Test.Unit/WebApi.Test.Unit.csproj
src/Directory.Packages.props
test/EasilyNET.Test.Unit/DeepCopy/ComplexClassTests.cs

在 `WebApi.Test.Unit.csproj` 中，更新了 `Microsoft.AspNetCore.Authentication.JwtBearer` 和 `Microsoft.Extensions.Caching.StackExchangeRedis` 的版本。
在 `Directory.Packages.props` 中，更新了多个 `Microsoft.Extensions` 相关的包版本。
在 `ComplexClassTests.cs` 中，移除了对 `Microsoft.VisualStudio.TestTools.UnitTesting` 的引用，并优化了断言语句，提高了代码的可读性和准确性。

feat: .NET 10 Preview6

---

src/Directory.Packages.props
test/EasilyNET.Core.Benchmark/EasilyNET.Core.Benchmark.csproj

更新 `Directory.Packages.props` 和 `EasilyNET.Core.Benchmark.csproj` 文件中的 `MongoDB.Driver` 包版本，从 `3.4.0` 升级到 `3.4.1`。同时，`Spectre.Console.Json` 包的版本也从 `0.50.1-preview.0.20` 升级到 `0.50.1-preview.0.21`。

feat: 升级包版本

---

Build.ps1

在 `Build.ps1` 文件中，移除了对 `EasilyNET.Ipc` 项目的打包命令，并添加了相同的命令。此更改仅涉及代码格式，没有影响命令的执行状态。

feat: 调整构建脚本

---

src/Directory.Packages.props

从 `Directory.Packages.props` 文件中移除了 `Polly.Core` 包的版本信息，版本号为 `8.6.2`。

clear: 清除cpm中未使用的包.

---

test/EasilyNET.Test.Unit/EasilyNET.Test.Unit.csproj

在 `EasilyNET.Test.Unit.csproj` 文件中，将 MSTest 的适配器和框架的版本从 `4.0.0-preview.25415.9` 更新为 `4.0.0-preview.25454.2`。

chore: 更新 MSTest 适配器和框架版本

---

src/EasilyNET.RabbitBus.AspNetCore/RabbitServiceExtension.cs

缩短了心跳间隔时间，将 `RequestedHeartbeat` 从 30 秒调整为 10 秒，以更快检测连接问题。 新增了 `ContinuationTimeout` 属性，设置为 5 秒，用于定义请求超时时间，提高系统响应性和稳定性。

chore: 优化 RabbitMQ 客户端连接配置

---

src/EasilyNET.RabbitBus.AspNetCore/RabbitServiceExtension.cs

修改了 `RabbitServiceExtension` 类中的配置逻辑：
- 保持 `factory.RequestedHeartbeat` 为 10 秒不变。
- 将 `factory.ContinuationTimeout` 从 5 秒增加到 20 秒。
- 更新注释，明确超时时间应大于等于心跳间隔的 1.5-2 倍。
此次变更旨在优化连接稳定性并提升代码可读性。

chore: 调整 RabbitMQ 超时配置以提高稳定性

---

sample/WebApi.Test.Unit/ServiceModules/OpenTelemetryModule.cs

在 OpenTelemetryModule.cs 文件中，更新了 OpenTelemetry 配置。 在调用 WithMetrics 方法时，c.AddMeter 的参数列表中新增了
"EasilyNET.RabbitBus"，以支持监控该指标源的相关数据。

feat: 新增 EasilyNET.RabbitBus 指标源到 OpenTelemetry 配置

---

test/EasilyNET.Core.Benchmark/EasilyNET.Core.Benchmark.csproj

更新了 `EasilyNET.Core.Benchmark.csproj` 文件中的 `BenchmarkDotNet` 包版本，从 `0.15.3` 升级到了 `0.15.4`，以利用新版本的改进和修复。

chore: 升级 BenchmarkDotNet 至 0.15.4

---

src/EasilyNET.Security/README.md
src/EasilyNET.Security/SM3/Sm3Signature.cs
test/EasilyNET.Test.Unit/Security/Sm3Test.cs

将 `Sm3Signature` 类中的方法从 `Signature` 重命名为 `Hash`，并同步更新相关方法（如 `SignatureToHex` -> `HashToHex`，`SignatureToBase64` -> `HashToBase64`）。更新了方法的 XML 注释以反映更改。
更新了 `README.md` 和 `Sm3Test.cs` 中的示例代码和测试代码以使用新的方法名称。所有调用代码均已同步调整，代码逻辑保持不变，仅优化了命名和注释以提高可读性。

chore: 重命名方法以更准确反映 SM3 哈希功能
