README.md, Test/Test.csproj, src/EasilyNET.AutoDependencyInjection/EasilyNET.AutoDependencyInjection.csproj
=> add .net 8.0

Directory.Build.props, src/EasilyNET.IdentityServer.MongoStorage/MongoRepository.cs, src/EasilyNET.IdentityServer.MongoStorage/RepositoryExtensions.cs
ids mongo add collection prefix parameter
=> ids mongo add collection prefix parameter

Test/EasilyNET.Tools.Test.Unit/ChineseLunar/ChineseLunarTest.cs
=> gb2312 -> utf8 with bom

Test/EasilyNET.Extensions.Test.Unit/EasilyNET.Extensions.Test.Unit.csproj, src/EasilyNET.Security/MD5.cs, src/EasilyNET.Security/SHA.cs, src/EasilyNET.Security/TripleDES.cs
=> upgrade code

Directory.Build.props, src/EasilyNET.Core/BaseType/IDictionaryExtensions.cs, src/EasilyNET.Core/BaseType/IEnumerableExtensions.cs, src/EasilyNET.Core/Language/CustomIntEnumeratorExtension.cs
=> 消除一些警告,以及调整intforeach迭代器的问题

Directory.Build.props, Test/WebApi.Test.Unit/WebApi.Test.Unit.csproj, src/EasilyNET.AutoDependencyInjection/EasilyNET.AutoDependencyInjection.csproj, src/EasilyNET.Core/EasilyNET.Core.csproj, src/EasilyNET.Core/Initialization/IniHelper.cs, src/EasilyNET.Mongo.Extension/EasilyNET.Mongo.Extension.csproj, src/EasilyNET.Mongo.GridFS.Extension/EasilyNET.Mongo.GridFS.Extension.csproj, src/EasilyNET.Mongo.GridFS/EasilyNET.Mongo.GridFS.csproj, src/EasilyNET.Mongo/EasilyNET.Mongo.csproj, src/EasilyNET.RabbitBus.Core/EasilyNET.RabbitBus.Core.csproj, src/EasilyNET.RabbitBus/EasilyNET.RabbitBus.csproj
=> up to .net8-preview.3

Directory.Build.props, Test/WebApi.Test.Unit/EventHandlers/RabbitEventHandlers.cs, Test/WebApi.Test.Unit/Events/RabbitEvents.cs, Test/WebApi.Test.Unit/ServiceModules/MongoFSModule.cs, src/EasilyNET.IdentityServer.MongoStorage/EasilyNET.IdentityServer.MongoStorage.csproj, src/EasilyNET.RabbitBus.Core/Attributes/DeadLetterAttribute.cs, src/EasilyNET.RabbitBus.Core/Attributes/RabbitExchangeArgAttribute.cs, src/EasilyNET.RabbitBus.Core/IIntegrationEvent.cs, src/EasilyNET.RabbitBus.Core/IIntegrationEventDeadLetterHandler.cs, src/EasilyNET.RabbitBus.Core/IntegrationEvent.cs, src/EasilyNET.RabbitBus/IntegrationEventBus.cs, src/EasilyNET.RabbitBus/Manager/DeadLetterSubscriptionsManager.cs, src/EasilyNET.RabbitBus/PersistentConnection.cs, src/EasilyNET.RabbitBus/ServiceCollectionExtension.cs
=> feat: 消息总线新增死信队列配置支持.

Directory.Build.props, Test/WebApi.Test.Unit/ServiceModules/MongoModule.cs, src/EasilyNET.Mongo/ServiceCollectionExtensions.cs
=> feat: bug fix

.vscode/launch.json, Directory.Build.props, src/EasilyNET.AutoDependencyInjection/PropertyInjection/PropertyInjectionServiceProvider.cs
=> fix: 修复属性注入可能会出现的空值异常

Directory.Build.props, Test/WebApi.Test.Unit/AppWebModule.cs, Test/WebApi.Test.Unit/Program.cs, Test/WebApi.Test.Unit/WebApi.Test.Unit.csproj, src/EasilyNET.AutoDependencyInjection.Core/Attributes/InjectionAttribute.cs, src/EasilyNET.AutoDependencyInjection/Abstractions/IPropertyInjector.cs, src/EasilyNET.AutoDependencyInjection/PropertyInjection/PropertyInjectionControllerFactory.cs, src/EasilyNET.AutoDependencyInjection/PropertyInjection/PropertyInjectionServiceProvider.cs, src/EasilyNET.AutoDependencyInjection/PropertyInjection/PropertyInjectionServiceProviderFactory.cs, src/EasilyNET.AutoDependencyInjection/PropertyInjection/PropertyInjector.cs, src/EasilyNET.AutoDependencyInjection/README.md, src/EasilyNET.RabbitBus.Core/Attributes/RabbitAttribute.cs, src/EasilyNET.WebCore/ApplicationBuilderExtensions.cs
style: 修复一些代码风格.
refactor: 删除一些无效代码.
=> style: 修复一些代码风格. refactor: 删除一些无效代码.

README.md
=> 📝 : 更新Emoji提交规范文档

Build.ps1
=> :hammer: 构建脚本添加

README.md, src/EasilyNET.Security/AES/AESModel.cs, src/EasilyNET.Security/AES/AesCrypt.cs, src/EasilyNET.Security/DES/DesCrypt.cs, src/EasilyNET.Security/DES/TripleDES.cs, src/EasilyNET.Security/RC4/Rc4Crypt.cs
=> :recycle: 重构代码

src/EasilyNET.Security/SM2/Sm2Model.cs
git config core.ignorecase false
=> 解决git不区分大小的问题

build/version.props, sample/WebApi.Test.Unit/AppWebModule.cs, sample/WebApi.Test.Unit/Program.cs, sample/WebApi.Test.Unit/ServiceModules/OutPutCachingModule.cs, src/EasilyNET.Mongo.ConsoleDebug/Attributes/ITemplateTokenRenderer.cs, src/EasilyNET.Mongo.ConsoleDebug/Extensions/RenderableCollection.cs, src/EasilyNET.Mongo.ConsoleDebug/Renderers/EventPropertyTokenRenderer.cs, src/EasilyNET.Mongo.ConsoleDebug/Renderers/ExceptionTokenRenderer.cs, src/EasilyNET.Mongo.ConsoleDebug/Renderers/LevelTokenRenderer.cs, src/EasilyNET.Mongo.ConsoleDebug/Renderers/MessageTemplateOutputTokenRenderer.cs, src/EasilyNET.Mongo.ConsoleDebug/Renderers/NewLineTokenRenderer.cs, src/EasilyNET.Mongo.ConsoleDebug/Renderers/PropertyTemplateRenderer.cs, src/EasilyNET.Mongo.ConsoleDebug/Renderers/RendersCommon.cs, src/EasilyNET.Mongo.ConsoleDebug/Renderers/TextTokenRenderer.cs, src/EasilyNET.Mongo.ConsoleDebug/Renderers/TimestampTokenRenderer.cs, src/EasilyNET.Mongo.ConsoleDebug/SpectreConsoleSink.cs, src/EasilyNET.Mongo.ConsoleDebug/Style/Casing.cs, src/EasilyNET.Mongo.ConsoleDebug/Style/DefaultStyle.cs, src/EasilyNET.Mongo.ConsoleDebug/Style/LevelOutputFormat.cs
:art: 调整Console.Debug库的输出内容以及格式
:bug: 修复Console.Debug库的链接会出现很多引号的问题.
=> 修复一些Console.Debug库的问题.

sample/WebApi.Test.Unit/WebApi.Test.Unit.csproj, src/EasilyNET.AutoDependencyInjection.Core/EasilyNET.AutoDependencyInjection.Core.csproj, src/EasilyNET.Core/EasilyNET.Core.csproj, src/EasilyNET.EntityFrameworkCore/EasilyNET.EntityFrameworkCore.csproj, src/EasilyNET.Mongo.AspNetCore/EasilyNET.Mongo.AspNetCore.csproj, src/EasilyNET.Mongo.ConsoleDebug/EasilyNET.Mongo.ConsoleDebug.csproj, src/EasilyNET.MongoSerializer.AspNetCore/EasilyNET.MongoSerializer.AspNetCore.csproj, src/EasilyNET.RabbitBus.AspNetCore/EasilyNET.RabbitBus.AspNetCore.csproj, test/EasilyNET.EntityFrameworkCore.Test/EasilyNET.EntityFrameworkCore.Test.csproj
=> :arrow_up: 升级.NET8 RC2

build/version.props, src/EasilyNET.IdentityServer.MongoStorage/IRepository.cs, src/EasilyNET.IdentityServer.MongoStorage/MongoRepository.cs
=> 更新ids部分接口的可见性.

src/EasilyNET.EntityFrameworkCore/Extensions/ServiceCollectionExtensions.cs, src/EasilyNET.EntityFrameworkCore/Options/EFCoreOptions.cs
=> 修复Options命名。

.github/release-drafter.yml
This commit updates the release-drafter configuration file to include a name-template and tag-template. It also modifies the categories and change-template sections.
=> Update release-drafter configuration***

src/EasilyNET.AutoDependencyInjection.Core/Abstractions/IScopedDependency.cs, src/EasilyNET.AutoDependencyInjection.Core/Abstractions/ISingletonDependency.cs, src/EasilyNET.AutoDependencyInjection.Core/Abstractions/ITransientDependency.cs, src/EasilyNET.AutoDependencyInjection.Core/Attributes/DependencyInjectionAttribute.cs, src/EasilyNET.AutoDependencyInjection/Modules/AppModule.cs, src/EasilyNET.AutoDependencyInjection/Modules/DependencyAppModule.cs, src/EasilyNET.AutoDependencyInjection/README.md
fix: 修复通过接口注入的一些错误.
feat: 依赖注入添加SelfOnly字段,可减少非必要的注入提升性能.
=> fix: 修复通过接口注入的一些错误.

EasilyNET.sln, src/EasilyNET.Core/Threading/AsyncLock.cs, src/EasilyNET.Core/Threading/AsyncSemaphore.cs, test/EasilyNET.Core.Benchmark/EasilyNET.Core.Benchmark.csproj, test/EasilyNET.Core.Benchmark/Program.cs, test/EasilyNET.Test/AsyncLockTest.cs, test/EasilyNET.Test/EasilyNET.Test.csproj
AsyncLock这个类的作用，只允许单个线程处理数据
我认为AsyncSemaphore可以使用无锁的方式得以提高性能，以下测试
以及相应的单元测试
=> 使用无锁的指令优化性能

src/EasilyNET.Core/Misc/TextWriterExtensions.cs
同时优化,当未设置最大宽度的情况下,宽度超过100后,强制设置为最大宽度的一半,若是一半后低于100则强制调整为100,避免太宽反而不好看.
=> fix: 修复ShowProgressBar在存在中文的情况下宽度计算错误的问题.

src/EasilyNET.Core/Misc/TextWriterExtensions.cs
=> fix: 修复光标定位错误问题.

sample/WebApi.Test.Unit/Program.cs, src/EasilyNET.Core/Misc/AssemblyHelper.cs
feat: AssemblyHelper新增LoadFromAllDll和AddAssemblyNames(params IEnumerable<string> names)用于手动控制反射范围,加快程序启动速度.
=> feat: AssemblyHelper新增LoadFromAllDll和AddAssemblyNames用于手动控制反射范围,加快程序启动速度.

src/Directory.Packages.props, test/EasilyNET.Test.Unit/EasilyNET.Test.Unit.csproj, test/EasilyNET.Test.Unit/InfoItems/ReferenceItemTest.cs, test/EasilyNET.Test.Unit/Misc/ObjectExtensionTest.cs, test/EasilyNET.Test.Unit/Misc/RmbCapitalizedTest.cs, test/EasilyNET.Test.Unit/Numerics/BigNumberTest.cs, test/EasilyNET.Test.Unit/PageResult/PageResultTests.cs, test/EasilyNET.Test.Unit/Security/Rc4Test.cs, test/EasilyNET.Test.Unit/Security/RsaTest.cs, test/EasilyNET.Test.Unit/Security/Sm2Test.cs, test/EasilyNET.Test.Unit/Security/Sm3Test.cs, test/EasilyNET.Test.Unit/Security/Sm4Test.cs, test/EasilyNET.Test.Unit/System/SnowFlakeIdTest.cs, test/EasilyNET.Test.Unit/System/SnowIdTest.cs, test/EasilyNET.Test.Unit/Threading/AsyncLockTest.cs
由于FluentAssertions的收费策略,将来会永久性移除FluentAssertions
=> feat: 永久性移除FluentAssertions,暂时调整为Shouldly

sample/WebApi.Test.Unit/ServiceModules/ControllersModule.cs, src/EasilyNET.Core/Misc/DateTimeStampExtensions.cs, src/EasilyNET.Core/Misc/RandomExtensions.cs, src/EasilyNET.RabbitBus.AspNetCore/RabbitServiceExtension.cs, test/EasilyNET.Test.Unit/Essentials/AsyncBarrierTest.cs
- 在 `ControllersModule.cs` 和 `RabbitServiceExtension.cs` 中添加了条件检查，以确保仅在适当的日志级别下记录日志。
- 在 `DateTimeStampExtensions.cs` 中添加了代码分析抑制特性，并改进了条件语句的可读性。
- 在 `RandomExtensions.cs` 中调整了返回值的计算方式，增加了括号以明确运算顺序。
- 在 `AsyncBarrierTest.cs` 中将异常断言方法更改为精确匹配异常类型。
=> feat: 优化日志记录和异常处理

sample/WebApi.Test.Unit/ServiceModules/OpenTelemetryModule.cs, src/EasilyNET.Core/Essentials/SnowId.cs, src/EasilyNET.Core/IDCard/IDCardCalculate.cs, src/EasilyNET.Core/IDCard/IDCardValidation.cs, src/EasilyNET.Core/Misc/DateTimeExtensions.cs, src/EasilyNET.Core/Misc/DateTimeStampExtensions.cs, src/EasilyNET.Core/Misc/EnumExtensions.cs, src/EasilyNET.Core/Misc/IConvertibleExtensions.cs, src/EasilyNET.Core/Misc/IEnumerableExtensions.cs, src/EasilyNET.Core/Misc/StringExtensions.cs, src/EasilyNET.Core/Numerics/BigNumber.cs, src/EasilyNET.Mongo.AspNetCore/Serializers/DateOnlySerializer.cs, src/EasilyNET.Mongo.AspNetCore/Serializers/TimeOnlySerializer.cs, src/EasilyNET.Mongo.ConsoleDebug/Subscribers/ActivityEventConsoleDebugSubscriber.cs, src/EasilyNET.RabbitBus.AspNetCore/Manager/SubscriptionsManager.cs, src/EasilyNET.RabbitBus.Core/Attributes/ExchangeAttribute.cs, src/EasilyNET.WebCore/JsonConverters/BoolJsonConverter.cs
- 将 `OpenTelemetryModule` 类改为 `static`，并添加 `OpenTelemetryExtensions` 类以支持 MongoDB 仪表化。
- 更新 `SnowId` 结构中的 `Equals` 和 `GetHashCode` 方法以符合 C# 9.0 语法。
- 修复 `IDCardCalculate` 类中的身份证号处理逻辑，提升可读性。
- 格式化 `DateTimeExtensions` 类中的属性和方法，增强可读性。
- 增强 `DateTimeStampExtensions` 和 `EnumExtensions` 类的健壮性。
- 优化 `IConvertibleExtensions` 和 `IEnumerableExtensions` 类的逻辑，确保代码简洁。
- 格式化 `StringExtensions`、`BigNumber`、`ActivityEventConsoleDebugSubscriber`、`SubscriptionsManager`、`ExchangeAttribute` 和 `BoolJsonConverter` 类中的方法，提升一致性和可读性。
=> chore: 优化代码结构和可读性

sample/WebApi.Test.Unit/WebApi.Test.Unit.csproj, src/Directory.Packages.props, src/EasilyNET.Core/Essentials/SnowId.cs
在 `WebApi.Test.Unit.csproj` 中，将 `Swashbuckle.AspNetCore` 的版本从 `8.1.1` 更新到 `8.1.2`。
在 `Directory.Packages.props` 中，更新以下包的版本：
- `Spectre.Console.Json` 从 `0.50.1-preview.0.5` 更新到 `0.50.1-preview.0.8`
- `Swashbuckle.AspNetCore.SwaggerGen` 从 `8.1.1` 更新到 `8.1.2`
- `Swashbuckle.AspNetCore.SwaggerUI` 从 `8.1.1` 更新到 `8.1.2`
=> feat: 更新依赖包版本

EasilyNET.sln.DotSettings, sample/WebApi.Test.Unit/Program.cs, sample/WebApi.Test.Unit/WebApi.Test.Unit.csproj, src/Directory.Packages.props, src/EasilyNET.Core/Misc/LunarCalendarHelper.cs, src/EasilyNET.Mongo.AspNetCore/CollectionIndexExtensions.cs, src/EasilyNET.Mongo.AspNetCore/MongoServiceExtensions.cs, test/EasilyNET.Test.Unit/BaseType/DateTimeExtensionTest.cs, test/EasilyNET.Test.Unit/EasilyNET.Test.Unit.csproj
在 `EasilyNET.sln.DotSettings` 中添加语法和拼写检查设置，更新用户字典。简化 `Program.cs` 中的 `OnShutdown` 方法实现，使用表达式体语法。更新 `WebApi.Test.Unit.csproj` 和 `Directory.Packages.props` 中的 `Swashbuckle.AspNetCore` 相关包版本至 `8.1.3`。在 `LunarCalendarHelper.cs` 中添加 ReSharper 禁用指令，优化日神获取逻辑。增强 `CollectionIndexExtensions.cs` 的健壮性，添加跳过未标记索引特性的逻辑。重命名 `MongoServiceExtensions.cs` 中的变量以提升可读性。修改 `DateTimeExtensionTest.cs` 的命名空间以更好组织测试代码，并更新 `Microsoft.NET.Test.Sdk` 至 `17.14.1`。
=> feat: 更新配置和依赖项,优化代码可读性,优化集合创建方式,若未配置索引,默认不生成,仅当数据插入时自动生成.

src/EasilyNET.Mongo.AspNetCore/CollectionIndexExtensions.cs
在 `CollectionIndexExtensions` 类中，修改了 `GenerateRequiredIndexes` 方法，新增 `bool isTimeSeries` 参数，以更好地支持时序集合的索引生成。同时，简化了 `ManageIndexes` 方法的参数列表，并在多个方法中调整了逻辑，确保时序集合不支持稀疏索引的规则得以强化。其他相关方法也进行了相应的更新，以适应新的索引生成需求。
=> fix: 优化时序集合索引处理逻辑

EasilyNET.sln.DotSettings, src/EasilyNET.Core/Numerics/BigNumber.cs, test/EasilyNET.Test.Unit/IDCard/IDCardCalculateTest.cs, test/EasilyNET.Test.Unit/Numerics/BigNumberTest.cs
在 `EasilyNET.sln.DotSettings` 中添加了用户字典词条 `fxor`。
在 `BigNumber.cs` 中引入了 `IEquatable` 和 `IComparable` 接口，改进了构造函数和运算符重载，支持分数和位运算。 更新了 `IDCardCalculateTests` 测试类以确保与当前日期一致性，并在 `BigNumberTest` 中添加了对分数运算的测试用例。
=> chore: 增强 BigNumber 类功能并更新测试用例,新增移位和异或运算符支持.

src/Directory.Packages.props, test/EasilyNET.Core.Benchmark/EasilyNET.Core.Benchmark.csproj, test/EasilyNET.Test.Unit/EasilyNET.Test.Unit.csproj
https://github.com/mongodb/mongo-csharp-driver/releases/tag/v3.4.2
=> feat: 更新MongoDB驱动

src/EasilyNET.Core/Coordinate/CoordinateConvert.cs, src/EasilyNET.Core/Threading/AsyncLock.cs, src/EasilyNET.Security/SM2/Sm2Crypt.cs, test/EasilyNET.Test.Unit/BaseType/AssemblyHelperTests.cs, test/EasilyNET.Test.Unit/BaseType/DateTimeExtensionTest.cs, test/EasilyNET.Test.Unit/DeepCopy/ModerateClassTests.cs, test/EasilyNET.Test.Unit/DeepCopy/SimpleClassTests.cs, test/EasilyNET.Test.Unit/Essentials/AsyncBarrierTest.cs, test/EasilyNET.Test.Unit/InfoItems/ReferenceItemTest.cs, test/EasilyNET.Test.Unit/Language/CustomIntEnumeratorTest.cs, test/EasilyNET.Test.Unit/Misc/ObjectExtensionTest.cs, test/EasilyNET.Test.Unit/Misc/RmbCapitalizedTest.cs, test/EasilyNET.Test.Unit/Misc/TypeExtensionTest.cs, test/EasilyNET.Test.Unit/Numerics/BigNumberTest.cs, test/EasilyNET.Test.Unit/PageResult/PageResultTests.cs, test/EasilyNET.Test.Unit/Security/Rc4Test.cs, test/EasilyNET.Test.Unit/Security/RsaTest.cs, test/EasilyNET.Test.Unit/Security/Sm2Test.cs, test/EasilyNET.Test.Unit/Security/Sm3Test.cs, test/EasilyNET.Test.Unit/Security/Sm4Test.cs, test/EasilyNET.Test.Unit/Threading/AsyncLockTest.cs
在 `AsyncLock.cs` 中添加了 `System.Runtime.CompilerServices` 引用，更新了文档注释，强调新的异步锁实现。移除了对 `SemaphoreSlim` 的依赖，改为使用自定义的锁状态管理，确保线程安全。修改了 `IsHeld` 和 `WaitingCount` 属性的实现，改进了 `Dispose` 方法以正确处理等待任务。引入 `Waiter` 类以管理等待锁的任务，整体上提升了代码的结构和逻辑。
=> feat: 优化 AsyncLock 实现,提高性能和可维护性

src/EasilyNET.Core/Misc/AssemblyHelper.cs
修改了文档注释，增加了功能概述的详细列表，提升了可读性。将与 LoadFromAllDll 相关的描述更新为使用 AssemblyScanOptions.ScanAllRuntimeLibraries。同时，添加了对传入参数的 null 检查，以增强代码的健壮性。
=> feat: 更新 AssemblyHelper.cs 文档注释和参数检查

src/EasilyNET.RabbitBus.AspNetCore/Manager/PersistentConnection.cs
通过引入 `_connectionReadyTcs` 和 `_reconnectTask`，提升了并发调用的稳定性，避免频繁抛出异常。 新增 `_reconnectLock` 确保重连任务线程安全，优化了连接复用和重连控制逻辑。
调整 `GetChannelAsync` 和 `InitializeConnectionAsync`，支持等待连接就绪，减少资源浪费。 在异步方法中统一使用 `ConfigureAwait(false)`，优化上下文切换。
增强日志记录，提供更详细的错误信息和状态更新。
=> chore: 优化 PersistentConnection 的连接管理逻辑

sample/WebApi.Test.Unit/ServiceModules/RabbitModule.cs, src/EasilyNET.RabbitBus.AspNetCore/Builder/RabbitBusBuilder.cs, src/EasilyNET.RabbitBus.AspNetCore/Configs/RabbitConfig.cs, src/EasilyNET.RabbitBus.AspNetCore/EventBus.cs, src/EasilyNET.RabbitBus.AspNetCore/Manager/ConsumerManager.cs, src/EasilyNET.RabbitBus.AspNetCore/Manager/EventPublisher.cs, src/EasilyNET.RabbitBus.AspNetCore/Manager/MessageConfirmManager.cs, src/EasilyNET.RabbitBus.AspNetCore/Manager/PersistentConnection.cs, src/EasilyNET.RabbitBus.AspNetCore/RabbitServiceExtension.cs
重构与新增功能：
- RabbitModule：动态设置 `WithApplication` 参数值，增强自定义序列化器支持。
- RabbitBusBuilder：新增 `WithRetryQueueSizing` 方法，支持重试队列容量的灵活配置。
- RabbitConfig：新增重试队列相关配置项，默认值更具动态性。
- EventBus：优化批量发布逻辑，简化代码。
- ConsumerManager：重构消费者启动逻辑，支持通道异常时自动重建。
- EventPublisher：新增快速重试机制，增强事件发布的异常处理与重试支持。
- MessageConfirmManager：动态调整重试队列容量，移除全局超时依赖。
- PersistentConnection：优化通道与连接管理，新增专用通道创建方法，增强重连逻辑。
- RabbitServiceExtension：支持动态设置 `ClientProvidedName`。
整体提升了系统的稳定性、可配置性与错误恢复能力。
=> chore: 优化 RabbitMQ 消息队列的重试与连接逻辑,并添加自动重新投递.

src/EasilyNET.Security/AES/AesCrypt.cs, src/EasilyNET.Security/AES/AesKeyModel.cs, src/EasilyNET.Security/AES/README.md, src/EasilyNET.Security/DES/DesCrypt.cs, src/EasilyNET.Security/DES/TripleDes.cs, src/EasilyNET.Security/RC4/Rc4Crypt.cs
- 在 `AesCrypt` 类中新增 AES192 密钥模式支持，扩展 AES128 和 AES256。
- 为 `AesCrypt`、`DesCrypt`、`TripleDes` 和 `Rc4Crypt` 类新增字符串加密/解密便捷方法，支持 Base64 和 Hex 编码。
- 优化密钥和 IV 的生成逻辑，使用 `stackalloc` 和 `Span<T>` 提升性能。
- 在 `Rc4Crypt` 类中新增基于密码的加密/解密方法，并引入密钥缓存机制。
- 在 `DesCrypt` 和 `TripleDes` 类中重命名密钥生成方法为更具描述性的名称。
- 增加安全性警告，提醒用户 DES、TripleDES 和 RC4 的安全风险。
- 改进异常处理逻辑，抛出更具描述性的 `ArgumentException`。
- 更新 `README.md`，新增 AES 使用指南、示例代码及 API 参考。
- 添加 ReSharper 禁用注释，优化代码注释为中英文双语。
=> chore: 新增 AES192 支持及加密解密功能优化

src/Directory.Packages.props, src/EasilyNET.Security/SM4/Sm4Crypt.cs
- 增加SM4加密算法的详细注释说明（中英双语）。
- 添加私有方法 `ValidateAndDecodeKey` 和 `ValidateAndDecodeIV`，用于验证和解码密钥及IV。
- 重构 `EncryptECB` 和 `DecryptECB`，移除重复逻辑。
- 为ECB模式新增字符串加密/解密功能：
- `EncryptECB` 支持字符串加密，返回字节数组、十六进制或Base64格式。
- `DecryptECB` 支持十六进制和Base64格式的解密。
- 为CBC模式新增字符串加密/解密功能：
- `EncryptCBC` 支持字符串加密，返回字节数组、十六进制或Base64格式。
- `DecryptCBC` 支持十六进制和Base64格式的解密。
- 改进所有公开方法的注释，明确密钥和IV的长度要求。
- 增加参数验证，确保输入有效性。
- 使用 `ArgumentException.ThrowIfNullOrWhiteSpace` 和 `ThrowIfNullOrEmpty` 提高代码可读性。
=> chore: 增强SM4加密功能并优化代码结构
